# Константы для локаций и врагов

# Локации
LOCATIONS = [
    {
        "name": "Лес Теней",
        "description": "Мрачный лес, полный опасностей. Здесь обитают слабые враги, подходящие для новичков.",
        "level_required": 1,
    },
    {
        "name": "Пещеры Глубин",
        "description": "Тёмные пещеры, где скрываются более сильные противники. Требуется опыт для выживания.",
        "level_required": 5,
    },
    {
        "name": "Замок Тьмы",
        "description": "Древний замок, населённый элитными воинами и могущественными боссами.",
        "level_required": 10,
    },
    {
        "name": "Вершина Дракона",
        "description": "Высокогорная крепость, где обитают легендарные существа. Только для опытных воинов.",
        "level_required": 15,
    },
    {
        "name": "Бездна Комет",
        "description": "Загадочное измерение, где время и пространство искажены. Самое опасное место во вселенной.",
        "level_required": 20,
    },
]

# Враги (мобы)
# Структура: name, description, type, health_multiplier, damage_multiplier, 
# coin_reward_multiplier, exp_reward_multiplier, drop_chance, location_names (список локаций)
ENEMIES = [
    # Лес Теней (уровень 1+)
    {
        "name": "Теневой Волк",
        "description": "Обычный волк, обитающий в тёмном лесу. Быстрый и агрессивный.",
        "type": "COMMON",
        "health_multiplier": 0.3,
        "damage_multiplier": 0.3,
        "coin_reward_multiplier": 0.5,
        "exp_reward_multiplier": 0.5,
        "drop_chance": 20.0,
        "location_names": ["Лес Теней"],
    },
    {
        "name": "Лесной Гоблин",
        "description": "Маленький, но хитрый гоблин. Любит нападать из засады.",
        "type": "COMMON",
        "health_multiplier": 0.4,
        "damage_multiplier": 0.35,
        "coin_reward_multiplier": 0.6,
        "exp_reward_multiplier": 0.6,
        "drop_chance": 25.0,
        "location_names": ["Лес Теней"],
    },
    {
        "name": "Вожак Стаи",
        "description": "Альфа-волк, возглавляющий стаю. Сильнее обычных волков.",
        "type": "ELITE",
        "health_multiplier": 0.8,
        "damage_multiplier": 0.7,
        "coin_reward_multiplier": 1.5,
        "exp_reward_multiplier": 1.5,
        "drop_chance": 40.0,
        "location_names": ["Лес Теней"],
    },
    
    # Пещеры Глубин (уровень 5+)
    {
        "name": "Пещерный Паук",
        "description": "Огромный паук, плетущий сети в глубинах пещер.",
        "type": "COMMON",
        "health_multiplier": 0.6,
        "damage_multiplier": 0.5,
        "coin_reward_multiplier": 0.8,
        "exp_reward_multiplier": 0.8,
        "drop_chance": 30.0,
        "location_names": ["Пещеры Глубин"],
    },
    {
        "name": "Троглодит-Воин",
        "description": "Примитивный воин подземного племени. Силён и вынослив.",
        "type": "COMMON",
        "health_multiplier": 0.7,
        "damage_multiplier": 0.6,
        "coin_reward_multiplier": 1.0,
        "exp_reward_multiplier": 1.0,
        "drop_chance": 35.0,
        "location_names": ["Пещеры Глубин"],
    },
    {
        "name": "Король Троглодитов",
        "description": "Могущественный правитель подземного племени. Опасный противник.",
        "type": "ELITE",
        "health_multiplier": 1.2,
        "damage_multiplier": 1.0,
        "coin_reward_multiplier": 2.0,
        "exp_reward_multiplier": 2.0,
        "drop_chance": 50.0,
        "location_names": ["Пещеры Глубин"],
    },
    
    # Замок Тьмы (уровень 10+)
    {
        "name": "Тёмный Рыцарь",
        "description": "Рыцарь, служащий силам тьмы. Обладает мощной броней и оружием.",
        "type": "COMMON",
        "health_multiplier": 1.0,
        "damage_multiplier": 0.9,
        "coin_reward_multiplier": 1.5,
        "exp_reward_multiplier": 1.5,
        "drop_chance": 40.0,
        "location_names": ["Замок Тьмы"],
    },
    {
        "name": "Элитный Страж",
        "description": "Элитный воин замка. Обучен лучшими мастерами боевых искусств.",
        "type": "ELITE",
        "health_multiplier": 1.5,
        "damage_multiplier": 1.3,
        "coin_reward_multiplier": 2.5,
        "exp_reward_multiplier": 2.5,
        "drop_chance": 55.0,
        "location_names": ["Замок Тьмы"],
    },
    {
        "name": "Лорд Тьмы",
        "description": "Владыка замка. Один из самых могущественных врагов в регионе.",
        "type": "BOSS",
        "health_multiplier": 3.0,
        "damage_multiplier": 2.5,
        "coin_reward_multiplier": 5.0,
        "exp_reward_multiplier": 5.0,
        "drop_chance": 80.0,
        "location_names": ["Замок Тьмы"],
    },
    
    # Вершина Дракона (уровень 15+)
    {
        "name": "Драконий Охотник",
        "description": "Опытный охотник, специализирующийся на драконах. Опасный противник.",
        "type": "COMMON",
        "health_multiplier": 1.3,
        "damage_multiplier": 1.2,
        "coin_reward_multiplier": 2.0,
        "exp_reward_multiplier": 2.0,
        "drop_chance": 45.0,
        "location_names": ["Вершина Дракона"],
    },
    {
        "name": "Драконий Рыцарь",
        "description": "Рыцарь, заключивший договор с драконами. Обладает их силой.",
        "type": "ELITE",
        "health_multiplier": 2.0,
        "damage_multiplier": 1.8,
        "coin_reward_multiplier": 3.5,
        "exp_reward_multiplier": 3.5,
        "drop_chance": 60.0,
        "location_names": ["Вершина Дракона"],
    },
    {
        "name": "Древний Дракон",
        "description": "Легендарный дракон, живущий тысячи лет. Невероятно могущественное существо.",
        "type": "BOSS",
        "health_multiplier": 5.0,
        "damage_multiplier": 4.0,
        "coin_reward_multiplier": 8.0,
        "exp_reward_multiplier": 8.0,
        "drop_chance": 90.0,
        "location_names": ["Вершина Дракона"],
    },
    
    # Бездна Комет (уровень 20+)
    {
        "name": "Искажённый Элементаль",
        "description": "Существо из искажённого измерения. Его природа непонятна.",
        "type": "COMMON",
        "health_multiplier": 1.8,
        "damage_multiplier": 1.6,
        "coin_reward_multiplier": 3.0,
        "exp_reward_multiplier": 3.0,
        "drop_chance": 50.0,
        "location_names": ["Бездна Комет"],
    },
    {
        "name": "Хранитель Бездны",
        "description": "Элитный страж искажённого измерения. Защищает его тайны.",
        "type": "ELITE",
        "health_multiplier": 2.8,
        "damage_multiplier": 2.5,
        "coin_reward_multiplier": 5.0,
        "exp_reward_multiplier": 5.0,
        "drop_chance": 70.0,
        "location_names": ["Бездна Комет"],
    },
    {
        "name": "Повелитель Бездны",
        "description": "Верховное существо искажённого измерения. Самое опасное создание во вселенной.",
        "type": "BOSS",
        "health_multiplier": 8.0,
        "damage_multiplier": 6.0,
        "coin_reward_multiplier": 12.0,
        "exp_reward_multiplier": 12.0,
        "drop_chance": 95.0,
        "location_names": ["Бездна Комет"],
    },
]

